{
    "openapi": "3.0.3",
    "info": {
        "title": "Soil AI RESTful API",
        "version": "1",
        "description": "OpenAPI for Soil AI RESTful API with MQTT functionality"
    },
    "servers": [
        {
            "description": "Soil AI API Server",
            "url": "https://{environment}/api/",
            "variables": {
                "environment": {
                    "description": "Server Environment",
                    "default": "127.0.0.1:8000",
                    "enum": ["127.0.0.1:8000", "soilapi.hcorp.my.id"]
                }
            }
        }
    ],
    "paths": {
        "/get_collect_data": {
            "get": {
                "tags": ["HTTP"],
                "summary": "Get all collect data",
                "description": "Get all active collect data, with optional filtering by temperature, air humidity, etc.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "ID of the collect data to filter by",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "temperature",
                        "in": "query",
                        "description": "Temperature to filter the data by",
                        "required": false,
                        "schema": {
                            "type": "number",
                            "format": "float"
                        }
                    },
                    {
                        "name": "air_humidity",
                        "in": "query",
                        "description": "Air humidity to filter the data by",
                        "required": false,
                        "schema": {
                            "type": "number",
                            "format": "float"
                        }
                    },
                    {
                        "name": "soil_humidity",
                        "in": "query",
                        "description": "Soil humidity to filter the data by",
                        "required": false,
                        "schema": {
                            "type": "number",
                            "format": "float"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved collect data",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "description": "Example success get all collect data",
                                        "value": [
                                            {
                                                "id": 1,
                                                "temperature": 92.0,
                                                "air_humidity": 12.0,
                                                "soil_humidity": 234.0
                                            },
                                            {
                                                "id": 2,
                                                "temperature": 14.0,
                                                "air_humidity": 45.0,
                                                "soil_humidity": 81.0
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/send_collect_data": {
            "post": {
                "tags": ["HTTP"],
                "summary": "Send new collect data",
                "description": "Send new collect data entry to the database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CollectData"
                            },
                            "examples": {
                                "data": {
                                    "description": "Example create collect data",
                                    "value": {
                                        "temperature": 25.0,
                                        "air_humidity": 60.0,
                                        "soil_humidity": 40.0
                                    }
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "Successfully created collect data",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/CollectData"
                                    },
                                    "examples": {
                                        "data": {
                                            "description": "Successfully created collect data",
                                            "value": {
                                                "data": {
                                                    "status": "success",
                                                    "message": "Send to collect data successfully"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/get_average_daily": {
            "get": {
                "tags": ["HTTP"],
                "summary": "Get average daily data",
                "description": "Get average daily data within the specified date range.",
                "parameters": [
                    {
                        "name": "start_date",
                        "in": "query",
                        "description": "Start date for the data range (YYYY-MM-DD)",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "date"
                        }
                    },
                    {
                        "name": "end_date",
                        "in": "query",
                        "description": "End date for the data range (YYYY-MM-DD)",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "date"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved average daily data",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "description": "Example success response",
                                        "value": [
                                            {
                                                "date": "2024-01-12",
                                                "average_temperature": 25.5,
                                                "average_air_humidity": 60.2,
                                                "average_soil_humidity": 45.8,
                                                "average_light": 300.0
                                            },
                                            {
                                                "date": "2024-01-13",
                                                "average_temperature": 26.0,
                                                "average_air_humidity": 58.0,
                                                "average_soil_humidity": 47.0,
                                                "average_light": 305.0
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "No data found for the specified date range",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "error": {
                                        "description": "Example error response",
                                        "value": {
                                            "status": "error",
                                            "message": "No average daily data found for the specified date range."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/mqtt_subscribe": {
            "post": {
                "tags": ["MQTT"],
                "summary": "Subscribe to an MQTT topic",
                "description": "Subscribe to a specified MQTT topic to start receiving messages.",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "topic": {
                                        "type": "string",
                                        "example": "collect/data",
                                        "description": "The MQTT topic to subscribe to"
                                    }
                                },
                                "required": ["topic"]
                            },
                            "examples": {
                                "data": {
                                    "description": "Example subscribe to MQTT topic",
                                    "value": {
                                        "topic": "collect/data"
                                    }
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "description": "Successfully subscribed to the topic",
                            "content": {
                                "application/json": {
                                    "examples": {
                                        "success": {
                                            "description": "Successfully subscribed",
                                            "value": {
                                                "status": "success",
                                                "message": "Successfully subscribed to collect/data"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/mqtt_publish": {
            "post": {
                "tags": ["MQTT"],
                "summary": "Publish a message to an MQTT topic",
                "description": "Publish a message to a specified MQTT topic.",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "topic": {
                                        "type": "string",
                                        "example": "collect/data",
                                        "description": "The MQTT topic to publish to"
                                    },
                                    "message": {
                                        "type": "string",
                                        "example": "{\"temperature\": 25.0, \"air_humidity\": 60.0}",
                                        "description": "The message to send"
                                    }
                                },
                                "required": ["topic", "message"]
                            },
                            "examples": {
                                "data": {
                                    "description": "Example publish to MQTT topic",
                                    "value": {
                                        "topic": "collect/data",
                                        "message": "{\"temperature\": 25.0, \"air_humidity\": 60.0, \"soil_humidity\": 223.0, \"light\": 1260.0}"
                                    }
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "description": "Successfully published the message",
                            "content": {
                                "application/json": {
                                    "examples": {
                                        "success": {
                                            "description": "Successfully published message",
                                            "value": {
                                                "status": "success",
                                                "message": "Message published to collect/data"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/send_message": {
            "post": {
                "tags": ["HTTP"],
                "summary": "Send a message",
                "description": "Send a message and receive a response.",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "message": {
                                        "type": "string",
                                        "example": "The plant is dry",
                                        "description": "The message content to send"
                                    }
                                },
                                "required": ["message"]
                            },
                            "examples": {
                                "data": {
                                    "description": "Example message",
                                    "value": {
                                        "message": "The plant is dry"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "description": "Successfully sent message",
                                        "value": {
                                            "status": "success",
                                            "message": "Send to Artificial Intellegence successfully"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid message format",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "error": {
                                        "description": "Error response for invalid message format",
                                        "value": {
                                            "status": "error",
                                            "message": "Invalid message format"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Error response when no average data is found.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "error": {
                                        "description": "Error response when no average data is found",
                                        "value": {
                                            "status": "error",
                                            "message": "No average data found for today."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/get_message_data": {
            "get": {
                "tags": ["HTTP"],
                "summary": "Get a message",
                "description": "Retrieve a message and its details.",
                "responses": {
                    "200": {
                        "description": "Message retrieved successfully",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "description": "Successfully retrieved message",
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "message": "The plant is dry",
                                                "average_id": 1,
                                                "created_at": "2024-12-19T10:00:00Z",
                                                "updated_at": "2024-12-19T10:00:00Z"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/get_message_latest": {
            "get": {
                "tags": ["HTTP"],
                "summary": "Get a last message",
                "description": "Retrieve a last message and its details.",
                "responses": {
                    "200": {
                        "description": "last Message retrieved successfully",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "description": "Successfully retrieved last message",
                                        "value": {
                                            "data": {
                                                "id": 2,
                                                "message": "Nothing can do",
                                                "average_id": 2,
                                                "created_at": "2024-12-19T10:00:00Z",
                                                "updated_at": "2024-12-19T10:00:00Z"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "CollectData": {
                "type": "object",
                "properties": {
                    "temperature": {
                        "type": "number",
                        "format": "float",
                        "example": 25.0
                    },
                    "air_humidity": {
                        "type": "number",
                        "format": "float",
                        "example": 60.0
                    },
                    "soil_humidity": {
                        "type": "number",
                        "format": "float",
                        "example": 40.0
                    },
                    "light": {
                        "type": "number",
                        "format": "float",
                        "example": 300.0
                    }
                },
                "required": [
                    "temperature",
                    "air_humidity",
                    "soil_humidity",
                    "light"
                ]
            }
        }
    }
}
